version: '3.7'
services:
  hazelcast-node1:
    container_name: node1
    image: 'hazelcast/hazelcast:latest'
    environment:
      - 'HZ_NETWORK_PUBLICADDRESS=192.168.0.103:5701'
      - HZ_CLUSTERNAME=lab2
    ports:
      - "5701:5701"
    networks:
      - labs

  hazelcast-node2:
    container_name: node2
    image: 'hazelcast/hazelcast:latest'
    environment:
      - 'HZ_NETWORK_PUBLICADDRESS=192.168.0.103:5702'
      - HZ_CLUSTERNAME=lab2
    ports:
      - "5702:5701"
    networks:
      - labs

  hazelcast-node3:
    container_name: node3
    image: 'hazelcast/hazelcast:latest'
    environment:
      - 'HZ_NETWORK_PUBLICADDRESS=192.168.0.103:5703'
      - HZ_CLUSTERNAME=lab2
    ports:
      - "5703:5701"
    networks:
      - labs

  management-center:
    container_name: mgmt
    image: hazelcast/management-center:latest
    environment:
      - MC_HTTP_PORT=8080
    ports:
      - "8080:8080"
    networks:
      - labs

networks:
  labs:
    driver: bridge
